config/routes.rb
Rails.application.routes.draw do
   resources :restaurants do
    resources :reviews, only: [:index, :new, :create]
  end
  resources :reviews, only: [:show, :edit, :update]
end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = @restaurant.reviews
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant, notice: "Restaurant was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :phone_number, :category)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end

  def show
    @review = Review.find(params[:id])
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
       if @review.save
      redirect_to @review, notice: "Review was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    def review_params
      params.require(:review).permit(:content, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/create.html.erb
<div class="container mt-4">
  <% if @restaurant.save %>
    <div class="alert alert-success">
      Restaurant was successfully created.
    </div>
  <% else %>
    <div class="alert alert-danger">
      <%= render "new" %>
    </div>
  <% end %>
</div>

app/views/restaurants/index.html.erb
<%= link_to "New Restaurant", new_restaurant_path, class: "btn btn-primary" %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone Number</th>
      <th>Category</th>
    </tr>
  </thead>
  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.phone_number %></td>
        <td><%= restaurant.category %></td>
        <td><%= link_to "Show", restaurant_path(restaurant), class: "btn btn-secondary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/restaurants/new.html.erb
<div class="container mt-4">
  <h1>New Restaurant</h1>

  <%= simple_form_for @restaurant, html: {class: "form-horizontal"} do |form| %>
    <%= form.error_notification %>

    <%= form.input :name, required: true, label: "Name", input_html: {class: "form-control"} %>
    <%= form.input :address, required: true, label: "Address", input_html: {class: "form-control"} %>
    <%= form.input :phone_number, required: true, label: "Phone Number", input_html: {class: "form-control"} %>
    <%= form.input :category, required: true, label: "Category", input_html: {class: "form-control"} %>

    <%= form.button :submit, "Create Restaurant", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/restaurants/show.html.erb
<div class="container mt-4">
  <h1><%= @restaurant.name %></h1>
  <p><%= @restaurant.address %></p>
  <p><%= @restaurant.phone_number %></p>
  <p><%= @restaurant.category %></p>

  <%= link_to "Back", restaurants_path, class: "btn btn-secondary mb-4" %>

  <h2>Reviews</h2>
  <% @reviews.each do |review| %>
    <div class="card mt-4">
      <div class="card-body">
        <h5 class="card-title"><%= review.rating %> stars</h5>
        <p class="card-text"><%= review.content %></p>
      </div>
    </div>
  <% end %>
   <%= link_to "Add a review",  new_restaurant_review_path(@restaurant), class: "btn btn-secondary mb-4" %>
</div>

app/views/reviews/create.html.erb
<div class="container mt-4">
  <% if @review.save %>
    <div class="alert alert-success">
      Review was successfully created.
    </div>
  <% else %>
    <div class="alert alert-danger">
      <%= render "new" %>
    </div>
  <% end %>
</div>

app/views/reviews/index.html.erb
 <%# <%= link_to "New Review",   new_restaurant_review_path, class: "btn btn-primary" %> %>

<table class="table">
  <thead>
    <tr>
      <th>Rating</th>
      <th>Content</th>
    </tr>
  </thead>
  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.rating %></td>
        <td><%= review.content %></td>
        <td><%= link_to "Show", review_path(review), class: "btn btn-secondary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reviews/new.html.erb
<div class="container mt-4">
  <h1>New Review</h1>

  <%= simple_form_for [@restaurant, @review], html: {class: "form-horizontal"} do |form| %>
    <%= form.error_notification %>

    <%= form.input :rating, required: true, label: "Rating", input_html: {class: "form-control"} %>
    <%= form.input :content, required: true, label: "Content", input_html: {class: "form-control"} %>

    <%= form.button :submit, "Create Review", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/reviews/show.html.erb
<div class="container mt-4">
  <h1><%= @review.rating %> stars</h1>
  <p><%= @review.content %></p>

  <%# <%= link_to "Edit", edit_review_path(@review), class: "btn btn-secondary mb-4" %> %>
  <%# <%= link_to "Back", reviews_path, class: "btn btn-secondary mb-4" %> %>
</div>